// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package lxd

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName      *string                      `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType    *string                      `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion    *string                      `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug          *bool                        `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce          *bool                        `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError        *string                      `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars       map[string]string            `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars  []string                     `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Image                *string                      `mapstructure:"image" required:"true" cty:"image" hcl:"image"`
	ImageRemoteURL       *string                      `mapstructure:"image_remote_url" required:"false" cty:"image_remote_url" hcl:"image_remote_url"`
	ImageRemoteProtocol  *string                      `mapstructure:"image_remote_protocol" required:"false" cty:"image_remote_protocol" hcl:"image_remote_protocol"`
	ContainerName        *string                      `mapstructure:"container_name" required:"false" cty:"container_name" hcl:"container_name"`
	OutputImage          *string                      `mapstructure:"output_image" required:"false" cty:"output_image" hcl:"output_image"`
	PublishRemoteName    *string                      `mapstructure:"publish_remote_name" required:"false" cty:"publish_remote_name" hcl:"publish_remote_name"`
	RemoteName           *string                      `mapstructure:"remote_name" required:"false" cty:"remote_name" hcl:"remote_name"`
	DaemonAddress        *string                      `mapstructure:"daemon_address" required:"false" cty:"daemon_address" hcl:"daemon_address"`
	ClientCertFile       *string                      `mapstructure:"client_cert" required:"false" cty:"client_cert" hcl:"client_cert"`
	ClientKeyFile        *string                      `mapstructure:"client_key" required:"false" cty:"client_key" hcl:"client_key"`
	ServerCertFile       *string                      `mapstructure:"server_cert" required:"false" cty:"server_cert" hcl:"server_cert"`
	InsecureSkipVerify   *bool                        `mapstructure:"insecure_skip_verify" required:"false" cty:"insecure_skip_verify" hcl:"insecure_skip_verify"`
	Project              *string                      `mapstructure:"project" required:"false" cty:"project" hcl:"project"`
	Target               *string                      `mapstructure:"target" required:"false" cty:"target" hcl:"target"`
	Profile              *string                      `mapstructure:"profile" required:"false" cty:"profile" hcl:"profile"`
	Profiles             []string                     `mapstructure:"profiles" required:"false" cty:"profiles" hcl:"profiles"`
	LaunchConfig         map[string]string            `mapstructure:"launch_config" required:"false" cty:"launch_config" hcl:"launch_config"`
	LaunchDevices        map[string]map[string]string `mapstructure:"launch_devices" required:"false" cty:"launch_devices" hcl:"launch_devices"`
	VirtualMachine       *bool                        `mapstructure:"virtual_machine" required:"false" cty:"virtual_machine" hcl:"virtual_machine"`
	InstanceType         *string                      `mapstructure:"instance_type" required:"false" cty:"instance_type" hcl:"instance_type"`
	Ephemeral            *bool                        `mapstructure:"ephemeral" required:"false" cty:"ephemeral" hcl:"ephemeral"`
	BootTimeout          *string                      `mapstructure:"boot_timeout" required:"false" cty:"boot_timeout" hcl:"boot_timeout"`
	WaitForNetwork       *bool                        `mapstructure:"wait_for_network" required:"false" cty:"wait_for_network" hcl:"wait_for_network"`
	PublishProperties    map[string]string            `mapstructure:"publish_properties" required:"false" cty:"publish_properties" hcl:"publish_properties"`
	PublishAliases       []string                     `mapstructure:"publish_aliases" required:"false" cty:"publish_aliases" hcl:"publish_aliases"`
	PublishPublic        *bool                        `mapstructure:"publish_public" required:"false" cty:"publish_public" hcl:"publish_public"`
	CompressionAlgorithm *string                      `mapstructure:"compression_algorithm" required:"false" cty:"compression_algorithm" hcl:"compression_algorithm"`
	ReuseAlias           *bool                        `mapstructure:"reuse_alias" required:"false" cty:"reuse_alias" hcl:"reuse_alias"`
	SkipPublish          *bool                        `mapstructure:"skip_publish" required:"false" cty:"skip_publish" hcl:"skip_publish"`
	ExecEnvironment      map[string]string            `mapstructure:"exec_environment" required:"false" cty:"exec_environment" hcl:"exec_environment"`
	ExecUser             *uint32                      `mapstructure:"exec_user" required:"false" cty:"exec_user" hcl:"exec_user"`
	ExecGroup            *uint32                      `mapstructure:"exec_group" required:"false" cty:"exec_group" hcl:"exec_group"`
	ExecCwd              *string                      `mapstructure:"exec_cwd" required:"false" cty:"exec_cwd" hcl:"exec_cwd"`
	CommandWrapper       *string                      `mapstructure:"command_wrapper" required:"false" cty:"command_wrapper" hcl:"command_wrapper"`
	InitSleep            *string                      `mapstructure:"init_sleep" required:"false" cty:"init_sleep" hcl:"init_sleep"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"image":                      &hcldec.AttrSpec{Name: "image", Type: cty.String, Required: false},
		"image_remote_url":           &hcldec.AttrSpec{Name: "image_remote_url", Type: cty.String, Required: false},
		"image_remote_protocol":      &hcldec.AttrSpec{Name: "image_remote_protocol", Type: cty.String, Required: false},
		"container_name":             &hcldec.AttrSpec{Name: "container_name", Type: cty.String, Required: false},
		"output_image":               &hcldec.AttrSpec{Name: "output_image", Type: cty.String, Required: false},
		"publish_remote_name":        &hcldec.AttrSpec{Name: "publish_remote_name", Type: cty.String, Required: false},
		"remote_name":                &hcldec.AttrSpec{Name: "remote_name", Type: cty.String, Required: false},
		"daemon_address":             &hcldec.AttrSpec{Name: "daemon_address", Type: cty.String, Required: false},
		"client_cert":                &hcldec.AttrSpec{Name: "client_cert", Type: cty.String, Required: false},
		"client_key":                 &hcldec.AttrSpec{Name: "client_key", Type: cty.String, Required: false},
		"server_cert":                &hcldec.AttrSpec{Name: "server_cert", Type: cty.String, Required: false},
		"insecure_skip_verify":       &hcldec.AttrSpec{Name: "insecure_skip_verify", Type: cty.Bool, Required: false},
		"project":                    &hcldec.AttrSpec{Name: "project", Type: cty.String, Required: false},
		"target":                     &hcldec.AttrSpec{Name: "target", Type: cty.String, Required: false},
		"profile":                    &hcldec.AttrSpec{Name: "profile", Type: cty.String, Required: false},
		"profiles":                   &hcldec.AttrSpec{Name: "profiles", Type: cty.List(cty.String), Required: false},
		"launch_config":              &hcldec.AttrSpec{Name: "launch_config", Type: cty.Map(cty.String), Required: false},
		"launch_devices":             &hcldec.AttrSpec{Name: "launch_devices", Type: cty.Map(cty.String), Required: false},
		"virtual_machine":            &hcldec.AttrSpec{Name: "virtual_machine", Type: cty.Bool, Required: false},
		"instance_type":              &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"ephemeral":                  &hcldec.AttrSpec{Name: "ephemeral", Type: cty.Bool, Required: false},
		"boot_timeout":               &hcldec.AttrSpec{Name: "boot_timeout", Type: cty.String, Required: false},
		"wait_for_network":           &hcldec.AttrSpec{Name: "wait_for_network", Type: cty.Bool, Required: false},
		"publish_properties":         &hcldec.AttrSpec{Name: "publish_properties", Type: cty.Map(cty.String), Required: false},
		"publish_aliases":            &hcldec.AttrSpec{Name: "publish_aliases", Type: cty.List(cty.String), Required: false},
		"publish_public":             &hcldec.AttrSpec{Name: "publish_public", Type: cty.Bool, Required: false},
		"compression_algorithm":      &hcldec.AttrSpec{Name: "compression_algorithm", Type: cty.String, Required: false},
		"reuse_alias":                &hcldec.AttrSpec{Name: "reuse_alias", Type: cty.Bool, Required: false},
		"skip_publish":               &hcldec.AttrSpec{Name: "skip_publish", Type: cty.Bool, Required: false},
		"exec_environment":           &hcldec.AttrSpec{Name: "exec_environment", Type: cty.Map(cty.String), Required: false},
		"exec_user":                  &hcldec.AttrSpec{Name: "exec_user", Type: cty.Number, Required: false},
		"exec_group":                 &hcldec.AttrSpec{Name: "exec_group", Type: cty.Number, Required: false},
		"exec_cwd":                   &hcldec.AttrSpec{Name: "exec_cwd", Type: cty.String, Required: false},
		"command_wrapper":            &hcldec.AttrSpec{Name: "command_wrapper", Type: cty.String, Required: false},
		"init_sleep":                 &hcldec.AttrSpec{Name: "init_sleep", Type: cty.String, Required: false},
	}
	return s
}
